version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build: ./docker/postgres/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookey_db
    ports:
      - 5432:5432
    restart: always